apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicated-app
  labels:
    app: app
    type: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      type: backend
  template:
    metadata:
      name: app-pod
      labels:
        app: app
        type: backend
    spec:
      containers:
      - name: nginx
        image: nginx
