apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
    type: backend
    tier: 1
spec:
  replicas: 3
  selector:
    matchLabels:
      type: backend
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: backend
        tier: 1
    spec:
      containers:
      - name: nginx
        image: nginx
